export const allRecipes = [
    {name: "TaterTot Casserole", href: "recipePages.html?index=0",
        ingredients: [
            "Hamburg",
            "Tatertots",
            "Beef",
            "Cream of Mushroom",
            "Cheese",
            "Green Beans",
            "Sour Cream",
        ],
        instructions: [
            "Preheat oven to 350 F, cook hamburg on stove med-high stir for 7-10 or until completely browned.",
            "Pour beef into a 9x13in backing pan. Add in sour cream and spread evenly overtop (optional).",
            "Layer soup, green beans and tater tots evenly on top, sprinkle shredded cheese overtop.",
            "Bake in oven for 30-45 minutes or until taters tots are golden brown.",
            "Allow cassarole to cool before serving.",
        ],
        notes: [
            "Adding sour cream adds a delicoious combonation of creamy richness, tangy flavor and a nice coolness.",
            "you may use any size tater tots as long as they are arranged to cover dish.",
            "for extra crispy tater tots, broil for a few minutes during final cooking stage.",
            "(optional seaoning)while browning hamburger, add in 2 teaspoons of minced garlic,1 teaspoon black pepper, 1/4 teaspoon salt, and 1 teaspoon of italian seasoning for extra flavor.",
        ],
        category: "dinner",
        time: "moderate",
    },
    {name: "Caesar Salad", href: "recipePages.html?index=1",
        ingredients:[
            "Romaine Lettuce",
            "Parmesean",
            "Croutons",
            "Caesar Dressing",
        ],
        instructions:[
            "In a large bowl combine chopped romaine, grated parmesan, croutons and half the caesar dressing.",
            "Toss to combine, adjusting the texture as needed (If too dry, more dressing can be added; If too wet, add more parmesan).",
            "Once the salad has been mixed, place in a cool or room temperature bowl and finish with more croutons and shaved parmesan.",
            "Serve immediately for the best texture.",
        ],
        notes: [""],
        category: "lunch",
        time: "short"
    },
    {name: "Chocolate Cupcakes", href: "recipePages.html?index=2",
        ingredients:[
            "Flour",
            "Baking Powder",
            "Baking Soda",
            "Salt",
            "Sugar",
            "Butter",
            "Eggs",
            "Vanilla",
            "Milk",
            "Cocoa Powder"
        ],
        instructions: [
            "Preheat oven to 350 F",
            "In a large bowl, combine: flour, cocoa powder, baking powder, baking soda and salt. Mix until well-combined.",
            "Whisk together sugar and butter in a medium sized bowl until light and fluffy.",
            "Add eggs one at a time beating well after each. Stir in vanilla extract and the flour mixture in two parts, add milk and beat well.",
            "Using a greased muffin spoon batter into each spot 3/4 full.",
            "Bake for 15-17 minutes. Once the tops are springy, and the toothpick comes out clean with a few moist crumbs.",
            "Allow cupcakes to cool in pan for five minutes before removing them, then transfer to a wire cooling rack to finish cooling."
        ],
        notes: [
            "Cupcakes are good stored at room temperature for four day, or refridgerated for five days.",
        ],
        category: "dessert",
        time: "moderate"
    },
    {name: "Panzanella Salad", href: "recipePages.html?index=3",
        ingredients:[
            "Italian bread",
            "Tomatoes",
            "Shallots",
            "Garlic",
            "Dijon mustard",
            "Red wine vinegar",
            "Olive oil",
            "Basil",
            "Salt & Pepper"
        ],
        instructions: [
            "Dice the bread into bite sized pieces, toss in olive oil and lightly season. Arrange the bread on a sheet pan and bake at 400 degrees for 5 minutes or until lightly toasted, but still spongy.",
            "If using full size tomatoes dice roughly the same size as the bread, If using cherry tomatoes, slice in half. After slicing or dicing the tomatoes allow the juice to drain into a bowl and set the tomatoes aside.",
            "To prepare the basil, roll a bunch of fresh leaves and slice into a chiffonade.",
            "To create the vinaigrette combine the collected tomato juice, red wine vinegar, shallots, garlic, olive oil and dijon mustard.",
            "In a large bowl, combine the bread, tomatoes, basil, and vinaigrette, and toss to combine. Season the salad to taste, and allow it to sit for at least 15 minutes before plating.",
        ],
        notes: [""],
        category: "lunch",
        time: "short"
    },
    {name: "Sauce Bearnaise", href: "recipePages.html?index=4",
        ingredients:[
            "Butter",
            "Shallots",
            "Tarragon",
            "Black peppercorns",
            "White wine",
            "Salt & Pepper"
        ],
        instructions: [
            "To clarify the butter, melt it in a saucepan over medium heat, checking from time to time to prevent the butter from burning. Remove from the heat and skim off any froth that has floated to the surface. Pour off the remaining butterfat into a separate container, leaving the proteins settled at the bottom.",
            "To prepare the reduction, peel and chop the shallots. Strip the tarragon leaves from the stems, rough chop and set aside for the end. Crack the peppercorns using a mortar and pestle and set aside. In a small saucepan, combine the vinegar, white wine, herb stems, shallots, and the cracked peppercorns.",
            "Heat over medium flame until the mixture comes to a simmer. Continue reducing for 15-20 minutes or until the mixture has reduced by two-thirds. Once reduced, strain the mixture into a new container.",
            "Combine the egg yolk(s) with cold water in a small saucepan and whisk for 30 seconds or until light and frothy. Heat the saucepan over medium-high heat, whisking rapidly. The mixture will increase in volume and begin to thicken. Continue whisking rapidly for 5 seconds to ensure it is fully cooked. Remove the sauce pan from the heat and whisk for 20 seconds to cool.",
            "Ladle the clarified butter into the sauce pan while slowly stirring with the whisk. The sauce will begin to have a stiff texture. Add the tarragon reduction until the sauce has the right texture and desired flavor. Add the chopped tarragon to the sauce and stir to combine.",
            "Adjust the sauces flavors, it may need salt, white pepper or additional vinegar. If too acidic, lengthen with more fat or liquid. Set aside the finished sauce and hold warm until serving.",
        ],
        notes: [""],
        category: "dinner",
        time: "long"
    },
    {name: "Sheperds Pie", href: "recipePages.html?index=5",
        ingredients:[
            "Red potatoes",
            "Garlic",
            "Heavy cream",
            "Butter",
            "Shredded cheese",
            "Hamburg",
            "Beef",
            "Gravy",
            "Corn",
            "Salt & Pepper"
        ],
        instructions: [
            "Wash the red potatoes and cut into quarters before adding them into a pot of water and bringing it to a boil.",
            "In a separate sauce pan add together the minced garlic, heavy cream, salt (as well as any additional herbs and spices) and heat to a simmer.",
            "To test the doneness of the potatoes, poke them with a fork. If they are soft enough to mash, and they easily remove from the fork, they are ready to strain. This should take 25-40 minutes.",
            "Strain the softened potatoes and return them to the pot. Add the heavy cream from the saucepan and use a masher to combine. The potatoes should be soft enough that this could also be done with a whisk.",
            "Continue mixing until smooth and no large pieces remain. Once the cream is well combined, cube and add the cold butter to the pot.",
            "Whisk the potatoes thoroughly until all the butter is melted. It's important to whisk the butter in completely to prevent separation.",
            "Set the mashed potatoes aside and allow to cool.",
            "Next, brown the hamburg in a large skillet and set the oven to preheat at 375 F.",
            "Once browned, strain the hamburg and add it to a cassarole pan.",
            "Evenly cover the hamburg with corn and gravy.",
            "Afterwards, add the mashed potatoes. The mashed should reach all the way to the edges of the pan and have an even thickness all the way around. This helps to prevent the gravy from bubbling over the top. (you can add cheese if you would like)",
            "Bake at 375 F for 20-35 minutes or until a light crust has formed.",
            "Allow the pie to cool for at least 15 minututes before serving (and it always taste better leftover!)",
        ],
        notes: [""],
        category: "dinner",
        time: "moderate"
    },
]